export const BACKEND_ROUTES = {
    PARAPHRASE_API: "api/paraphrase/",
    OBJECTIVE_API: "api/shikshalokam/generate-objective/",
    ACTION_LIST_API: "api/shikshalokam/generate-action-list/",
    TITLE_API: "api/shikshalokam/generate-title/",
    SAVE_COMPANY_CHAT: "api/save-company-chat/",
    GET_COMPANY_CHAT: "api/companychat/",
    GENERATE_SESSION_ID: "api/generate-session/",
    CREATE_CHAT_SESSION: "api/create-chatsession/",
    CHAT_SESSION: "api/chatsession/",
    CREATE_PROJECT: "api/create-project/",
    VALIDATE_OBJECTIVE: "api/shikshalokam/validate-objective/",
    VALIDATE_ACTIONS: "api/shikshalokam/validate-actions/",
    VALIDATE_TITLE: "api/shikshalokam/validate-title/",
};
